### ISSUE TITLE
r_depthbits 32 -> render @ 0-1fps

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#137]
Author: @boutetnico (boutetnico)
Date: 2012-11-28
Redmine Issue: 137, https://dev.etlegacy.com/issues/137

---

Setting r_depthbits "32" on my Windows 7 x64 fresh ET:Legacy install makes the game rendering @ 0-1fps

It happens both on fs_game "legacy" and in ETrun mod.

r_depthbits "32" works well on my main ET install.

Can anyone confirm the bug?

---

Related commit(s):
646b92733c1c2acfa8097d6be340981d61bf5133 - renderer: fix for r_depthbits 32 refs 137

**Comment by ETLegacyTeam** [comment]
From: Mateos (Mateos)
Date: 2012-11-28T17:33:36Z

---

Tested on Oasis with the RC1, 90 FPS on 24 bits, same on 32 bits, and even did a vid_restart to check.

Only thing I had, but since default settings: entities have a kind of shadow in the mid-air above them on Oasis for me... Have to check if already reported.

**Comment by ETLegacyTeam** [comment]
From: @rafal1137 (RaFaL)
Date: 2012-11-29T01:22:34Z

---

Hmm I tested it and it look like there must be smth with 32 value I connected to etlegacy server and screen was all red
I builded ET Legacy from last git commit

PS: ETL RC1 same result

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2012-11-29T17:52:40Z

---

Looks like we have to add some code to sdl_glimp.c (line 330++). There is no case for r_depthbits "32" and we have to subtsract r_depthbits.

Update: 
1. Windows GPL code differs from ours
2. r_depthbits 32 isn't supported by all video cards (info from the internet)

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2013-05-10T12:00:01Z

---

I'm getting a display which wasn't the case on linux before this commit: http://www.etlegacy.com/projects/etlegacy/repository/revisions/646b92733c1c2acfa8097d6be340981d61bf5133/diff/src/sdl/sdl_glimp.c

Can someone test r_depthbits 32 on Windows?

**Comment by ETLegacyTeam** [comment]
From: @boutetnico (boutetnico)
Date: 2013-05-11T11:05:15Z

---

Tested on Windows 7 x64 with a compiled version from git repository, the issue is still the same, 0 to 1fps when r_depthbits is 32.

**Comment by ETLegacyTeam** [comment]
From: @saukko28 (Saukko)
Date: 2013-12-13T01:11:46Z

---

I tried this out with Windows 8.1 64-bit, without any luck.
In vanilla ET it works without any problems.
Though r_depthbits "32" can't even be chosen through the options menu. Maybe that possible could be added when the problem will be solved?

-*S

**Comment by ETLegacyTeam** [comment]
From: @yfcz (yfcz)
Date: 2016-03-09T15:17:14Z

---

Currently there is implemented test which determines if SDL_GL_CreateContext gets some OGL context. It doesn't care if it is HW accelerated or not.

There is GDI Generic renderer shipped with Windows which provides OpenGL 1.1 context without hardware acceleration. And it supports 32-bit depth buffer.

So if you try to use 32-bit depth buffer and drivers of your video card doesn't support it, it will use GDI OGL context — which has terrible performance since it has no HW acceleration.

---------------------------

The solution might be to distinguish accelerated and non-accelerated OGL contexts and use these accelerated only.
I've already implemented this, see my latest commit(s) at this branch: https://github.com/yfcz/etlegacy/commits/issue137
What do you think about this solution?

(If you're going to compile here are updated libs: https://github.com/yfcz/etlegacy-libs/commit/2d8c44cbafdbc39987096d5c562ec30302bbe653 )

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2016-03-15T07:57:19Z

---

The solution is fine but also a big blowing up of the source code for one value of a cvar which is marked as unsafe.

**Comment by rmarquis** [comment]
WGLext has been part of the etlegacy-libs repo for some time now. There is no need for more cmake adjustment, and the proposed fix at https://github.com/yfcz/etlegacy/commit/c804aea98de3a9632569271d6fb36935d75d8dac can be adjusted and implemented.

**Comment by isRyven** [comment]
Patch looks good to me. We should probably try it. People are still experiencing issue with `32` depthbits on window (coming from their configs), more specifically it leads to a fatal error since renderer cannot fetch the shader language version (https://github.com/etlegacy/etlegacy/blob/master/src/renderercommon/tr_common.c#L91), because of ogl1 context is being forced i assume. Other solution is just to fix the depthbits value to `24`.
