### ISSUE TITLE
show ready status in scoreboard

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1416]
its tedious to do this with players command in console
how it looks like in Q3 CPMA:
![shot-20200320-121819](https://user-images.githubusercontent.com/4035800/77159254-49e34280-6aa5-11ea-8436-3b938a1ca5c2.jpg)

**Comment by mittermichal** [comment]
so apparently its the running man icon
I didn't know this even though I play etpro stopwatch since 2008 :D

**Comment by rmarquis** [comment]
Reopening. The current icon is the antilag one, but we can surely use something better and less confusing.

**Comment by BystryPL** [comment]
This feature is now bugged, not always showing the icon even if players ready up.

**Comment by realkemon** [comment]
Since this has been reopened, may I semi-highjack this?
I had my first competitive experience yesterday and one thing I noticed is that when you are asked to "Press F3 to ready", the prompt does not disappear after being ready. I had to check console for feedback that I am now in fact ready as it prints "You are already ready" or sth like that on a second F3 press. Can the prompt be disabled?

**Comment by Aranud** [comment]
Related code : https://github.com/etlegacy/etlegacy/blob/81fe3bc079f76d8290016f11a55fc2474ee7169b/src/cgame/cg_scoreboard.c#L431-L437

There is a related issue where the gamestate isn't correctly sent to clients. It doesn't always happen and on map restart the problem is solved.

Since this part of code seems to never been touched, it could be hard to do something there.

**Comment by BystryPL** [comment]
Just noticed today that the bug still occurs (numbers of ready icons in scoreboard not consistent with the actual number of players that readied up).

**Comment by rmarquis** [comment]
Note: there is some slight delay between what the scoreboard displays and what is happening (~1 or 2 sec delay afair, and refreshed when you hit tab). The issue itself might have been fixed properly with the previous commit.

**Comment by ryzyk-krzysiek** [comment]
The isssue is quite rare but exists, it has happened over few months (I've seen it like 2-3 times at most), but I was unable to reproduce and have no idea what could be causing it.

Also another relevant changes: https://github.com/etlegacy/etlegacy/pull/1643

Note: start match vote if passed will not set ready state to true.
